package product;

public enum ProductCategory {
    TOYS_KIDS,
    SPORTS_OUTDOORS,
    HOME_GARDEN,
    HEALTH_BEAUTY,
    FOOD_BEVERAGES,
    FASHION,
    ELECTRONICS,
    BOOKS_MEDIA,
    AUTOMOTIVE_ACCESSORIES,
    APPLIANCES
}
